###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ bundle add baml sorbet-runtime
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# frozen_string_literal: true
# rubocop: disable
# formatter:off
module Baml
  module Inlined
    FILE_MAP = {
        
        "generators.baml" => "generator target {\n  output_type ruby/sorbet\n  output_dir \"..\"\n  version \"0.90.2\"\n}\n",
        "main.baml" => "class Problem {\n  type string @description(\"exposure, color, noise, blur, composition, artifacts\")\n  description string\n  location string @description(\"center, edges, background, foreground, overall\")\n}\n\nclass ImageAnalysis {\n  problems Problem[]\n  fix_instructions string @description(\"Consolidated instructions for fixing all problems\")\n}\n\nfunction AnalyzeImageProblems(img: image) -> ImageAnalysis {\n  client Gemini\n  prompt #\"\n    {{ _.role(\"user\") }}\n    Analyze this image for quality problems.\n\n    Check for:\n    - Exposure issues (over/underexposed)\n    - Color balance problems\n    - Noise or grain\n    - Blur or focus issues\n    - Composition problems\n    - Compression artifacts\n\n    {{ img }}\n\n    {{ ctx.output_format }}\n  \"#\n}\n\nfunction FixImageProblems(img: image, instructions: string) -> string {\n  client GeminiFlashImage\n  prompt #\"\n    {{ _.role(\"user\") }}\n    Fix this image according to these instructions:\n\n    {{ instructions }}\n\n    {{ img }}\n\n    Generate an improved version of the image.\n  \"#\n}\n\nclient<llm> Gemini {\n  provider google-ai\n  options {\n    api_key env.GOOGLE_AI_API_KEY\n    model \"gemini-2.0-flash\"\n  }\n}\n\nclient<llm> GeminiFlashImage {\n  provider google-ai\n  options {\n    api_key env.GOOGLE_AI_API_KEY\n    model \"gemini-2.0-flash-exp\"\n    generationConfig {\n      responseModalities [\"TEXT\", \"IMAGE\"]\n    }\n  }\n}\n",
    }
  end
end