###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ bundle add baml sorbet-runtime
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# frozen_string_literal: true
# rubocop: disable
# formatter:off
# typed: false
require "baml"
require "sorbet-runtime"

require_relative "type-registry"
require_relative "partial-types"
require_relative "types"

module Baml
  class LlmResponseParser
    extend T::Sig

    sig {params(runtime: Baml::Ffi::BamlRuntime, ctx_manager: Baml::Ffi::RuntimeContextManager).void}
    def initialize(runtime:, ctx_manager:)
      @runtime = runtime
      @ctx_manager = ctx_manager
    end

    sig {
      params(
        llm_response: String,
        baml_options: T::Hash[Symbol, T.any(Baml::TypeBuilder, Baml::ClientRegistry, T::Hash[Symbol, String])]
      ).returns(Baml::Types::ImageAnalysis)
    }
    def AnalyzeImageProblems(llm_response:, baml_options: {})
      if (baml_options.keys - [:client_registry, :tb, :env]).any?
        raise ArgumentError.new("Received unknown keys in baml_options (valid keys: :client_registry, :tb, :env): #{baml_options.keys - [:client_registry, :tb, :env]}")
      end

      @runtime.parse_llm_response(
        "AnalyzeImageProblems",
        llm_response,
        Baml::Types,
        Baml::PartialTypes,
        false,
        @ctx_manager,
        baml_options[:tb]&.instance_variable_get(:@registry),
        baml_options[:client_registry],
        baml_options[:env] || ENV.to_h
      )
    end

    sig {
      params(
        llm_response: String,
        baml_options: T::Hash[Symbol, T.any(Baml::TypeBuilder, Baml::ClientRegistry, T::Hash[Symbol, String])]
      ).returns(String)
    }
    def FixImageProblems(llm_response:, baml_options: {})
      if (baml_options.keys - [:client_registry, :tb, :env]).any?
        raise ArgumentError.new("Received unknown keys in baml_options (valid keys: :client_registry, :tb, :env): #{baml_options.keys - [:client_registry, :tb, :env]}")
      end

      @runtime.parse_llm_response(
        "FixImageProblems",
        llm_response,
        Baml::Types,
        Baml::PartialTypes,
        false,
        @ctx_manager,
        baml_options[:tb]&.instance_variable_get(:@registry),
        baml_options[:client_registry],
        baml_options[:env] || ENV.to_h
      )
    end

    
  end

  class LlmStreamParser
    extend T::Sig

    sig {params(runtime: Baml::Ffi::BamlRuntime, ctx_manager: Baml::Ffi::RuntimeContextManager).void}
    def initialize(runtime:, ctx_manager:)
      @runtime = runtime
      @ctx_manager = ctx_manager
    end

    sig {
      params(
        llm_response: String,
        baml_options: T::Hash[Symbol, T.any(Baml::TypeBuilder, Baml::ClientRegistry, T::Hash[Symbol, String])]
      ).returns(T.nilable(Baml::PartialTypes::ImageAnalysis))
    }
    def AnalyzeImageProblems(llm_response:, baml_options: {})
      if (baml_options.keys - [:client_registry, :tb, :env]).any?
        raise ArgumentError.new("Received unknown keys in baml_options (valid keys: :client_registry, :tb, :env): #{baml_options.keys - [:client_registry, :tb, :env]}")
      end

      @runtime.parse_llm_response(
        "AnalyzeImageProblems",
        llm_response,
        Baml::Types,
        Baml::PartialTypes,
        true,
        @ctx_manager,
        baml_options[:tb]&.instance_variable_get(:@registry),
        baml_options[:client_registry],
        baml_options[:env] || ENV.to_h
      )
    end

    sig {
      params(
        llm_response: String,
        baml_options: T::Hash[Symbol, T.any(Baml::TypeBuilder, Baml::ClientRegistry, T::Hash[Symbol, String])]
      ).returns(T.nilable(String))
    }
    def FixImageProblems(llm_response:, baml_options: {})
      if (baml_options.keys - [:client_registry, :tb, :env]).any?
        raise ArgumentError.new("Received unknown keys in baml_options (valid keys: :client_registry, :tb, :env): #{baml_options.keys - [:client_registry, :tb, :env]}")
      end

      @runtime.parse_llm_response(
        "FixImageProblems",
        llm_response,
        Baml::Types,
        Baml::PartialTypes,
        true,
        @ctx_manager,
        baml_options[:tb]&.instance_variable_get(:@registry),
        baml_options[:client_registry],
        baml_options[:env] || ENV.to_h
      )
    end

    
  end
end