###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ bundle add baml sorbet-runtime
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# frozen_string_literal: true
# rubocop: disable
# formatter:off
# typed: false
require "baml"
require "sorbet-runtime"

require_relative "type-registry"
require_relative "partial-types"
require_relative "types"

module Baml
  class HttpRequest
    extend T::Sig

    sig {params(runtime: Baml::Ffi::BamlRuntime, ctx_manager: Baml::Ffi::RuntimeContextManager).void}
    def initialize(runtime:, ctx_manager:)
      @runtime = runtime
      @ctx_manager = ctx_manager
    end

    sig {
      params(
        varargs: T.untyped,
        img: Baml::Image,
        baml_options: T::Hash[Symbol, T.any(Baml::TypeBuilder, Baml::ClientRegistry, T::Hash[Symbol, String])]
      ).returns(Baml::Ffi::HTTPRequest)
    }
    def AnalyzeImageProblems(
        *varargs,
        img:,
        baml_options: {}
    )
      if varargs.any?
        raise ArgumentError.new("AnalyzeImageProblems may only be called with keyword arguments")
      end
      if (baml_options.keys - [:client_registry, :tb, :env]).any?
        raise ArgumentError.new("Received unknown keys in baml_options (valid keys: :client_registry, :tb, :env): #{baml_options.keys - [:client_registry, :tb, :env]}")
      end

      @runtime.build_request(
        "AnalyzeImageProblems",
        {
          img: img,
        },
        @ctx_manager,
        baml_options[:tb]&.instance_variable_get(:@registry),
        baml_options[:client_registry],
        baml_options[:env] || ENV.to_h,
        false,
      )
    end

    sig {
      params(
        varargs: T.untyped,
        img: Baml::Image,instructions: String,
        baml_options: T::Hash[Symbol, T.any(Baml::TypeBuilder, Baml::ClientRegistry, T::Hash[Symbol, String])]
      ).returns(Baml::Ffi::HTTPRequest)
    }
    def FixImageProblems(
        *varargs,
        img:,instructions:,
        baml_options: {}
    )
      if varargs.any?
        raise ArgumentError.new("FixImageProblems may only be called with keyword arguments")
      end
      if (baml_options.keys - [:client_registry, :tb, :env]).any?
        raise ArgumentError.new("Received unknown keys in baml_options (valid keys: :client_registry, :tb, :env): #{baml_options.keys - [:client_registry, :tb, :env]}")
      end

      @runtime.build_request(
        "FixImageProblems",
        {
          img: img,instructions: instructions,
        },
        @ctx_manager,
        baml_options[:tb]&.instance_variable_get(:@registry),
        baml_options[:client_registry],
        baml_options[:env] || ENV.to_h,
        false,
      )
    end

    
  end

  class HttpStreamRequest
    extend T::Sig

    sig {params(runtime: Baml::Ffi::BamlRuntime, ctx_manager: Baml::Ffi::RuntimeContextManager).void}
    def initialize(runtime:, ctx_manager:)
      @runtime = runtime
      @ctx_manager = ctx_manager
    end

    sig {
      params(
        varargs: T.untyped,
        img: Baml::Image,
        baml_options: T::Hash[Symbol, T.any(Baml::TypeBuilder, Baml::ClientRegistry, T::Hash[Symbol, String])]
      ).returns(Baml::Ffi::HTTPRequest)
    }
    def AnalyzeImageProblems(
        *varargs,
        img:,
        baml_options: {}
    )
      if varargs.any?
        raise ArgumentError.new("AnalyzeImageProblems may only be called with keyword arguments")
      end
      if (baml_options.keys - [:client_registry, :tb, :env]).any?
        raise ArgumentError.new("Received unknown keys in baml_options (valid keys: :client_registry, :tb, :env): #{baml_options.keys - [:client_registry, :tb, :env]}")
      end

      @runtime.build_request(
        "AnalyzeImageProblems",
        {
          img: img,
        },
        @ctx_manager,
        baml_options[:tb]&.instance_variable_get(:@registry),
        baml_options[:client_registry],
        baml_options[:env] || ENV.to_h,
        true,
      )
    end

    sig {
      params(
        varargs: T.untyped,
        img: Baml::Image,instructions: String,
        baml_options: T::Hash[Symbol, T.any(Baml::TypeBuilder, Baml::ClientRegistry, T::Hash[Symbol, String])]
      ).returns(Baml::Ffi::HTTPRequest)
    }
    def FixImageProblems(
        *varargs,
        img:,instructions:,
        baml_options: {}
    )
      if varargs.any?
        raise ArgumentError.new("FixImageProblems may only be called with keyword arguments")
      end
      if (baml_options.keys - [:client_registry, :tb, :env]).any?
        raise ArgumentError.new("Received unknown keys in baml_options (valid keys: :client_registry, :tb, :env): #{baml_options.keys - [:client_registry, :tb, :env]}")
      end

      @runtime.build_request(
        "FixImageProblems",
        {
          img: img,instructions: instructions,
        },
        @ctx_manager,
        baml_options[:tb]&.instance_variable_get(:@registry),
        baml_options[:client_registry],
        baml_options[:env] || ENV.to_h,
        true,
      )
    end

    
  end
end