###############################################################################
#
#  Welcome to Baml! To use this generated code, please run the following:
#
#  $ bundle add baml sorbet-runtime
#
###############################################################################

# This file was generated by BAML: please do not edit it. Instead, edit the
# BAML files and re-generate this code.
#
# frozen_string_literal: true
# rubocop: disable
# formatter:off
# typed: false
require "sorbet-runtime"

module Baml
  
  module Types
    class ImageAnalysis < T::Struct; end
    class Problem < T::Struct; end
    class ImageAnalysis < T::Struct
      include Baml::Sorbet::Struct
      const :problems, T::Array[Baml::Types::Problem]
      const :fix_instructions, String

      def initialize(props)
        super(
          problems: props[:problems],
          fix_instructions: props[:fix_instructions],
        )

        @props = props
      end
    end
    class Problem < T::Struct
      include Baml::Sorbet::Struct
      const :type, String
      const :description, String
      const :location, String

      def initialize(props)
        super(
          type: props[:type],
          description: props[:description],
          location: props[:location],
        )

        @props = props
      end
    end

  end
end